# Generated by Django 3.1.6 on 2021-03-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0003_auto_20210301_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noon_product',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='noon_product',
            old_name='Buy_Box_Price',
            new_name='buy_box_Price',
        ),
        migrations.RenameField(
            model_name='noon_product',
            old_name='Buy_Box_seller',
            new_name='buy_box_seller',
        ),
        migrations.RenameField(
            model_name='noon_product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='noon_product',
            old_name='NOON_SKU',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='noon_product',
            old_name='Sold_quantity_last_day',
            new_name='sold_quantity_last_day',
        ),
        migrations.RemoveField(
            model_name='noon_product',
            name='Total_inventory',
        ),
        migrations.AddField(
            model_name='noon_product',
            name='total_inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
