# Generated by Django 3.1.6 on 2021-03-01 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0004_auto_20210301_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('sku', models.CharField(blank=True, max_length=250, null=True)),
                ('product_title', models.CharField(blank=True, max_length=250, null=True)),
                ('listing_url', models.CharField(blank=True, max_length=250, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('brand', models.CharField(blank=True, max_length=250, null=True)),
                ('report_date_time', models.CharField(blank=True, max_length=250, null=True)),
                ('no_of_sellers', models.IntegerField(blank=True, null=True)),
                ('no_of_fbn_sellers', models.IntegerField(blank=True, null=True)),
                ('buy_box_seller', models.CharField(blank=True, max_length=250, null=True)),
                ('buy_box_Price', models.IntegerField(blank=True, null=True)),
                ('total_inventory', models.IntegerField(blank=True, null=True)),
                ('sold_quantity_last_day', models.IntegerField(blank=True, null=True)),
                ('sold_qantity_last_7_day', models.IntegerField(blank=True, null=True)),
                ('sold_quantity_last_30_day', models.IntegerField(blank=True, null=True)),
                ('listing_with_incorrect_inventory', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='day',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noon_crawlers.product'),
        ),
        migrations.DeleteModel(
            name='NOON_PRODUCT',
        ),
    ]
