# Generated by Django 3.1.6 on 2021-03-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0006_fetchday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='sold_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
