# Generated by Django 3.1.6 on 2021-03-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0007_auto_20210301_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sold_qantity_last_7_day',
            new_name='sold_quantity_last_7_day',
        ),
    ]
