# Generated by Django 3.1.6 on 2021-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0008_auto_20210301_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='listing_with_incorrect_inventory',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
