# Generated by Django 3.1.6 on 2021-03-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0011_proxyports_bandwidth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyports',
            name='bandwidth',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
    ]
