# Generated by Django 3.1.6 on 2021-03-03 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0012_auto_20210303_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fetchday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
