# Generated by Django 3.1.6 on 2021-03-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0013_auto_20210304_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.CharField(default='March', max_length=25),
        ),
    ]
