# Generated by Django 3.1.6 on 2021-03-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0014_day_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxyports',
            old_name='bandwidth',
            new_name='bandwidth_utilized',
        ),
        migrations.AddField(
            model_name='proxyports',
            name='ending_bandwidth',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='proxyports',
            name='starting_bandwidth',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
    ]
