# Generated by Django 3.1.6 on 2021-03-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0019_product_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
