# Generated by Django 3.1.6 on 2021-03-28 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0020_auto_20210326_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('num_of_pages_scraped', models.IntegerField(default=0)),
                ('num_of_skus', models.IntegerField(default=0)),
                ('fully_scraped', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('fetch_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noon_crawlers.fetchday')),
            ],
        ),
    ]
