# Generated by Django 3.1.6 on 2021-03-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0021_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
