# Generated by Django 3.1.6 on 2021-03-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0022_category_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='fetch_day',
        ),
        migrations.AddField(
            model_name='category',
            name='fetch_day_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
