# Generated by Django 3.1.6 on 2021-05-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0023_auto_20210328_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='month',
            field=models.CharField(default='May', max_length=25),
        ),
        migrations.AlterField(
            model_name='day',
            name='month',
            field=models.CharField(default='May', max_length=25),
        ),
    ]
