# Generated by Django 3.1.6 on 2021-06-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0025_auto_20210610_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
