# Generated by Django 3.1.6 on 2021-06-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0026_auto_20210613_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchday',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
