# Generated by Django 3.1.6 on 2021-06-16 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_crawlers', '0028_auto_20210616_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 6, 17)),
        ),
    ]
